### PR TITLE
Check all password requirements in one attempt

### LINKED ISSUE #59: Check all requirements before throwing the exception
Right now we check the password validity we do this sequentially. So if one fails we return. See https://github.com/nextcloud/password_policy/blob/master/lib/PasswordValidator.php#L54-L60

It makes more sense I think to check them all and throw a combined exception. So you are told directly what is all wrong with your password

### PR DESCRIPTION
**Pull request by nickvergessen**
Console:
```
occ user:resetpassword admin
Enter a new password: 
Confirm the new password: 
Password needs to be at least 8 characters long. Password needs to contain at least one lower and one upper case character. Password needs to contain at least one special character. Password is present in compromised password list. Please choose a different password.
```

Web reset:
Bildschirmfoto von 2021-02-17 13-19-30

Web change:
Bildschirmfoto von 2021-02-17 13-20-14

Styling isn't the best everywhere, but that needs fixing in server.

Fix #59

### CODE REVIEW

File: lib/PasswordValidator.php [hunk 1]
```diff
@@ -73,8 +75,19 @@ public function validate(string $password): void {
...
+				$errors[] = $e->getMessage();
+				$hints[] = $e->getHint();
+			}
 		}
-	}
 
+		if (!empty($errors)) {
+			throw new HintException(
+				implode(' ', $errors),
+				implode(' ', $hints),
```
Comment (nickvergessen) [inline lib/PasswordValidator.php:89]: If we go with `\n` here, it would look better in the CLI, but the frontend doesn't understand that, so it would need fixing in the server as well to transform `\n` into `<br>` and allow html in first place

File: lib/Validator/LengthValidator.php [hunk 2]
```diff
@@ -43,9 +43,9 @@ public function __construct(PasswordPolicyConfig $config, IL10N $l) {
 	public function validate(string $password): void {
 		$minLength = $this->config->getMinLength();
 		if(strlen($password) < $minLength) {
-			$message = 'Password needs to be at least ' . $minLength . ' characters long';
+			$message = 'Password needs to be at least ' . $minLength . ' characters long.';
 			$message_t = $this->l->t(
-				'Password needs to be at least %s characters long', [$minLength]
+				'Password needs to be at least %s characters long.', [$minLength]
```
Comment (nickvergessen) [inline lib/Validator/LengthValidator.php:48]: doing that for consistency

File: lib/PasswordValidator.php (hunk 1 above)
Comment (rullzer) [reply lib/PasswordValidator.php:89]: Fine for now I'd say. Maybe we need a different kind of exception for this.

**Review by ChristophWurst — APPROVED** [review]
:+1: :elephant:
